export interface CulturePromo {
  id: string;
  title: string;
  location: string;
  latitude?: number;
  longitude?: number;
  color: string;
  icon: any;
  time?: string;
  price?: string;
  contact?: string;
  fullDescription?: string;
  category?: 'seni' | 'musik' | 'kuliner' | 'kerajinan' | 'all';
  discount?: string;
  description?: string;
  date?: string;
  activities?: string[];
  points?: number;
  completed?: boolean;
  points?: number;
}

export const promotions: CulturePromo[] = [
  {
    id: '1',
    title: 'Festival Budaya Bandung',
    location: 'Alun-alun Bandung',
    latitude: -6.9175,
    longitude: 107.6191,
    color: '#FF6B6B',
    icon: 'heart',
    time: 'Setiap Sabtu, 10:00 - 17:00',
    price: 'Gratis',
    contact: 'info@festivalbandung.org',
    fullDescription: 'Nikmati kekayaan budaya Sunda dengan berbagai pertunjukan seni, kuliner tradisional, dan pameran kerajinan tangan.',
    category: 'seni',
    discount: 'Early Bird 10%',
    description: 'Festival budaya tahunan dengan berbagai pertunjukan dan kuliner.',
    date: '2025-12-06',
    activities: ['Pertunjukan Tari', 'Pameran Kerajinan', 'Workshop Kuliner'],
    points: 10,
    completed: false
  },
  {
    id: '2',
    title: 'Workshop Batik Tradisional',
    location: 'Kampung Batik Cigadung',
    latitude: -6.8850,
    longitude: 107.6500,
    color: '#4ECDC4',
    icon: 'palette',
    time: 'Minggu, 09:00 - 12:00',
    price: 'Rp 150.000',
    contact: 'batik.cigadung@gmail.com',
    fullDescription: 'Pelajari seni membatik dari para pengrajin lokal dan buat batik Anda sendiri. Termasuk bahan dan peralatan.',
    category: 'kerajinan',
    description: 'Workshop interaktif untuk membuat batik.',
    date: '2025-12-07',
    activities: ['Pelatihan Membatik', 'Pembuatan Pola', 'Pewarnaan Kain'],
    points: 10,
    completed: false
  },
  {
    id: '3',
    title: 'Wisata Kuliner Malam Braga',
    location: 'Jalan Braga',
    latitude: -6.9147,
    longitude: 107.6098,
    color: '#A8E6CF',
    icon: 'utensils',
    time: 'Setiap Jumat & Sabtu, 18:00 - 22:00',
    price: 'Mulai Rp 50.000',
    contact: 'braga.kuliner@email.com',
    fullDescription: 'Jelajahi berbagai hidangan legendaris Bandung di sepanjang Jalan Braga yang bersejarah. Pemandu wisata tersedia.',
    category: 'kuliner',
    discount: 'Diskon 5% untuk pembelian kedua',
    description: 'Jelajahi kuliner malam di jantung kota Bandung.',
    date: '2025-12-05',
    activities: ['Food Tasting', 'Sejarah Kuliner', 'Jalan-jalan Malam'],
    points: 10,
    completed: false
  },
  {
    id: '4',
    title: 'Pertunjukan Angklung Udjo',
    location: 'Saung Angklung Udjo',
    latitude: -6.8920,
    longitude: 107.6750,
    color: '#FFEA00',
    icon: 'music',
    time: 'Setiap Hari, 15:30 - 17:00',
    price: 'Dewasa Rp 75.000, Anak-anak Rp 50.000',
    contact: 'reservasi@angklungudjo.com',
    fullDescription: 'Saksikan pertunjukan angklung yang memukau dan berpartisipasi dalam sesi interaktif yang menyenangkan.',
    category: 'musik',
    description: 'Pertunjukan angklung interaktif yang terkenal.',
    date: '2025-12-08',
    activities: ['Menonton Pertunjukan', 'Bermain Angklung', 'Belajar Sejarah Angklung'],
    points: 10,
    completed: false
  },
  {
    id: '5',
    title: 'Pameran Seni Kontemporer',
    location: 'Galeri Nasional Indonesia',
    latitude: -6.9150,
    longitude: 107.6050,
    color: '#B24592',
    icon: 'brush',
    time: 'Selasa - Minggu, 10:00 - 18:00',
    price: 'Gratis',
    contact: 'info@galerinasional.or.id',
    fullDescription: 'Temukan karya seni kontemporer dari seniman terkemuka Indonesia. Pameran berubah setiap bulan.',
    category: 'seni',
    description: 'Pameran karya seni dari seniman lokal dan nasional.',
    date: '2025-12-09',
    activities: ['Melihat Pameran', 'Diskusi Seniman', 'Workshop Seni'],
    points: 10,
    completed: false
  },
  {
    id: '6',
    title: 'Jelajah Sejarah Gedung Sate',
    location: 'Gedung Sate',
    latitude: -6.9025,
    longitude: 107.6189,
    color: '#6B4226',
    icon: 'building',
    time: 'Setiap Hari, 09:00 - 16:00',
    price: 'Rp 20.000',
    contact: 'tour@gedungsate.org',
    fullDescription: 'Tur berpemandu untuk mengenal sejarah dan arsitektur Gedung Sate, ikon Kota Bandung.',
    category: 'all',
    discount: 'Buy 2 Get 1 Free',
    description: 'Tur sejarah ikonik Gedung Sate.',
    date: '2025-12-10',
    activities: ['Tur Berpemandu', 'Foto Bersama', 'Kunjungan Museum'],
    points: 10,
    completed: false
  },
  {
    id: '7',
    title: 'Kelas Tari Tradisional Sunda',
    location: 'Sanggar Tari Parahyangan',
    latitude: -6.9200,
    longitude: 107.6250,
    color: '#FF8C00',
    icon: 'child',
    time: 'Setiap Senin & Rabu, 16:00 - 18:00',
    price: 'Rp 100.000/sesi',
    contact: 'sanggar.parahyangan@email.com',
    fullDescription: 'Belajar dasar-dasar tari jaipong dan tari merak dari instruktur profesional.',
    category: 'seni',
    description: 'Kelas tari tradisional Sunda.',
    date: '2025-12-11',
    activities: ['Pelatihan Tari', 'Koreografi', 'Pementasan'],
    points: 10,
    completed: false
  },
  {
    id: '8',
    title: 'Festival Film Indie Bandung',
    location: 'Pusat Kebudayaan Bandung',
    latitude: -6.9000,
    longitude: 107.6150,
    color: '#8A2BE2',
    icon: 'film',
    time: 'Setiap Akhir Bulan, 19:00 - Selesai',
    price: 'Rp 30.000',
    contact: 'info@filmindiebdg.com',
    fullDescription: 'Pemutaran film-film pendek independen karya sineas lokal dan diskusi dengan sutradara.',
    category: 'seni',
    description: 'Festival film independen.',
    date: '2025-12-12',
    activities: ['Pemutaran Film', 'Diskusi Sutradara', 'Networking'],
    points: 10,
    completed: false
  },
  {
    id: '9',
    title: 'Wisata Edukasi Tegalega',
    location: 'Taman Tegalega',
    latitude: -6.9350,
    longitude: 107.6050,
    color: '#00CED1',
    icon: 'tree',
    time: 'Setiap Hari, 08:00 - 17:00',
    price: 'Gratis',
    contact: 'tegalega.edukasi@email.com',
    fullDescription: 'Kunjungi Monumen Bandung Lautan Api dan area edukasi lingkungan di Taman Tegalega.',
    category: 'all',
    description: 'Wisata edukasi sejarah dan lingkungan.',
    date: '2025-12-13',
    activities: ['Kunjungan Monumen', 'Edukasi Lingkungan', 'Rekreasi'],
    points: 10,
    completed: false
  },
  {
    id: '10',
    title: 'Diskusi Sastra di Warung Kopi',
    location: 'Kopi Anjis',
    latitude: -6.9050,
    longitude: 107.6100,
    color: '#D2691E',
    icon: 'book',
    time: 'Setiap Kamis Malam, 20:00 - 22:00',
    price: 'Gratis (pesan minuman/makanan)',
    contact: 'kopi.anjis@email.com',
    fullDescription: 'Berkumpul dengan pecinta sastra untuk membahas buku dan karya tulis. Terbuka untuk umum.',
    category: 'seni',
    description: 'Diskusi sastra santai.',
    date: '2025-12-14',
    activities: ['Diskusi Buku', 'Pembacaan Puisi', 'Networking'],
    points: 10,
    completed: false
  },
  {
    id: '11',
    title: 'Pentas Wayang Golek',
    location: 'Padepokan Seni Mayang Sunda',
    latitude: -6.9100,
    longitude: 107.6100,
    color: '#CD5C5C',
    icon: 'mask',
    time: 'Setiap Sabtu, 19:00 - 21:00',
    price: 'Rp 50.000',
    contact: 'mayangsunda@gmail.com',
    fullDescription: 'Saksikan pertunjukan wayang golek tradisional yang mengisahkan epos Ramayana dan Mahabharata.',
    category: 'seni',
    description: 'Pertunjukan wayang golek.',
    date: '2025-12-15',
    activities: ['Menonton Pertunjukan', 'Edukasi Budaya', 'Interaksi dengan Dalang'],
    points: 10,
    completed: false
  },
  {
    id: '12',
    title: 'Lomba Fotografi Bandung Tempo Dulu',
    location: 'Museum Konferensi Asia Afrika',
    latitude: -6.9200,
    longitude: 107.6080,
    color: '#5F9EA0',
    icon: 'camera',
    time: 'Pendaftaran: Bulan Maret',
    price: 'Rp 75.000 (biaya pendaftaran)',
    contact: 'lomba.foto.bandung@email.com',
    fullDescription: 'Kompetisi fotografi untuk mengabadikan sudut-sudut kota Bandung dengan nuansa jadul. Berhadiah jutaan rupiah!',
    category: 'seni',
    description: 'Kompetisi fotografi.',
    date: '2025-12-16',
    activities: ['Memotret', 'Pameran Foto', 'Penjurian'],
    points: 10,
    completed: false
  },
  {
    id: '13',
    title: 'Festival Musik Jazz Bandung',
    location: 'Lapangan Gasibu',
    latitude: -6.9030,
    longitude: 107.6180,
    color: '#C71585',
    icon: 'guitar',
    time: 'Juli (cek jadwal)',
    price: 'Mulai Rp 100.000',
    contact: 'info@jazzbandung.com',
    fullDescription: 'Sajian musik jazz dari musisi nasional dan internasional di panggung terbuka.',
    category: 'musik',
    discount: 'Promo Mahasiswa 20%',
    description: 'Festival musik jazz tahunan.',
    date: '2025-12-17',
    activities: ['Menonton Konser', 'Workshop Musik', 'Meet & Greet'],
    points: 10,
    completed: false
  },
  {
    id: '14',
    title: 'Gebyar Budaya Jawa Barat',
    location: 'Gedung Sate',
    latitude: -6.9025,
    longitude: 107.6189,
    color: '#FF4500',
    icon: 'gopuram',
    time: 'Agustus (cek jadwal)',
    price: 'Gratis',
    contact: 'disparbud.jabar@go.id',
    fullDescription: 'Perayaan kebudayaan Jawa Barat dengan aneka tarian, musik, dan pameran kuliner khas.',
    category: 'seni',
    description: 'Perayaan budaya Jawa Barat.',
    date: '2025-12-18',
    activities: ['Pertunjukan Budaya', 'Pameran Kuliner', 'Workshop Tradisional'],
    points: 10,
    completed: false
  },
  {
    id: '15',
    title: 'Workshop Membatik Cap',
    location: 'Cihampelas Walk',
    latitude: -6.8960,
    longitude: 107.5990,
    color: '#20B2AA',
    icon: 'tshirt',
    time: 'Setiap Sabtu, 14:00 - 16:00',
    price: 'Rp 120.000',
    contact: 'cihampelas.walk@email.com',
    fullDescription: 'Pelajari teknik membatik cap yang lebih sederhana dan cepat, cocok untuk pemula.',
    category: 'kerajinan',
    discount: 'Diskon 10% untuk grup',
    description: 'Workshop membatik dengan teknik cap.',
    date: '2025-12-19',
    activities: ['Pelatihan Membatik', 'Pembuatan Karya', 'Diskusi'],
    points: 10,
    completed: false
  },
  {
    id: '16',
    title: 'Tur Sepeda Heritage Bandung',
    location: 'Titik Kumpul: Gedung Merdeka',
    latitude: -6.9210,
    longitude: 107.6085,
    color: '#DAA520',
    icon: 'bicycle',
    time: 'Setiap Minggu Pagi, 07:00 - 10:00',
    price: 'Rp 50.000 (sewa sepeda tidak termasuk)',
    contact: 'bandung.bike@tour.com',
    fullDescription: 'Jelajahi bangunan bersejarah Bandung dengan tur sepeda yang menyenangkan dan edukatif.',
    category: 'all',
    description: 'Tur sepeda keliling kota Bandung.',
    date: '2025-12-20',
    activities: ['Bersepeda', 'Kunjungan Sejarah', 'Fotografi'],
    points: 10,
    completed: false
  },
  {
    id: '17',
    title: 'Malam Puisi & Sastra',
    location: 'Institut Francais Indonesia (IFI)',
    latitude: -6.9050,
    longitude: 107.6070,
    color: '#4682B4',
    icon: 'microphone-alt',
    time: 'Setiap Selasa ke-2, 19:30 - 21:00',
    price: 'Gratis',
    contact: 'budaya.ifi@gmail.com',
    fullDescription: 'Pembacaan puisi dan diskusi sastra bersama komunitas dan penulis lokal.',
    category: 'seni',
    description: 'Malam apresiasi puisi dan sastra.',
    date: '2025-12-21',
    activities: ['Pembacaan Puisi', 'Diskusi Sastra', 'Networking'],
    points: 10,
    completed: false
  },
  {
    id: '18',
    title: 'Pentas Seni Anak Tradisional',
    location: 'Taman Budaya Jawa Barat',
    latitude: -6.9280,
    longitude: 107.6000,
    color: '#FF69B4',
    icon: 'child-reaching',
    time: 'Setiap Minggu, 14:00 - 16:00',
    price: 'Gratis',
    contact: 'tamanbudaya.jabar@go.id',
    fullDescription: 'Saksikan pertunjukan seni tradisional yang dibawakan oleh anak-anak, melestarikan budaya sejak dini.',
    category: 'seni',
    description: 'Pentas seni anak.',
    date: '2025-12-22',
    activities: ['Menonton Pertunjukan', 'Edukasi Anak', 'Foto Bersama'],
    points: 10,
    completed: false
  },
  {
    id: '19',
    title: 'Festival Komunitas Hobi Bandung',
    location: 'Balai Kota Bandung',
    latitude: -6.9120,
    longitude: 107.6090,
    color: '#ADFF2F',
    icon: 'users',
    time: 'September (cek jadwal)',
    price: 'Gratis',
    contact: 'komunitas.bdg@email.com',
    fullDescription: 'Berbagai komunitas hobi di Bandung berkumpul memamerkan aktivitas dan kreasi mereka.',
    category: 'all',
    description: 'Festival untuk komunitas hobi.',
    date: '2025-12-23',
    activities: ['Pameran Komunitas', 'Workshop', 'Pertunjukan'],
    points: 10,
    completed: false
  },
  {
    id: '20',
    title: 'Bazaar Produk Kreatif Lokal',
    location: 'Creative Hub Bandung',
    latitude: -6.9080,
    longitude: 107.6150,
    color: '#FFA07A',
    icon: 'store',
    time: 'Setiap Bulan, Jumat-Minggu',
    price: 'Gratis Masuk',
    contact: 'creativehub.bdg@email.com',
    fullDescription: 'Pameran dan penjualan produk-produk kreatif dari UMKM dan desainer lokal Bandung.',
    category: 'kerajinan',
    discount: 'Diskon 15% untuk pembelian di atas Rp 200.000',
    description: 'Bazaar produk kreatif lokal.',
    date: '2025-12-24',
    activities: ['Belanja Produk', 'Workshop Mini', 'Live Music'],
    points: 10,
    completed: false
  },
  {
    id: '21',
    title: 'Diskusi Sejarah Bandung',
    location: 'Perpustakaan Kota Bandung',
    latitude: -6.9100,
    longitude: 107.6050,
    color: '#6495ED',
    icon: 'landmark',
    time: 'Setiap Rabu ke-3, 15:00 - 17:00',
    price: 'Gratis',
    contact: 'perpus.bdg@email.com',
    fullDescription: 'Menggali lebih dalam sejarah Bandung bersama sejarawan dan komunitas.',
    category: 'all',
    description: 'Diskusi sejarah kota Bandung.',
    date: '2025-12-25',
    activities: ['Diskusi Panel', 'Sesi Tanya Jawab', 'Pameran Buku'],
    points: 10,
    completed: false
  },
  {
    id: '22',
    title: 'Kelas Memasak Makanan Sunda',
    location: 'Dapur Nyonya',
    latitude: -6.9250,
    longitude: 107.6200,
    color: '#7FFF00',
    icon: 'mortar-pestle',
    time: 'Setiap Kamis, 10:00 - 13:00',
    price: 'Rp 200.000',
    contact: 'dapurnyonya@email.com',
    fullDescription: 'Pelajari resep-resep otentik masakan Sunda dan praktik langsung membuatnya.',
    category: 'kuliner',
    description: 'Kelas memasak masakan Sunda.',
    date: '2025-12-26',
    activities: ['Memasak Bersama', 'Food Tasting', 'Resep Rahasia'],
    points: 10,
    completed: false
  },
  {
    id: '23',
    title: 'Pentas Teater Tradisional',
    location: 'Gedung Kesenian Rumentang Siang',
    latitude: -6.9200,
    longitude: 107.6050,
    color: '#DC143C',
    icon: 'theater-masks',
    time: 'Setiap Jumat Malam, 20:00 - 22:00',
    price: 'Rp 40.000',
    contact: 'rumentang.siang@email.com',
    fullDescription: 'Nikmati drama dan komedi tradisional Sunda yang sarat makna dan hiburan.',
    category: 'seni',
    description: 'Pertunjukan teater tradisional.',
    date: '2025-12-27',
    activities: ['Menonton Teater', 'Diskusi Aktor', 'Foto Bersama'],
    points: 10,
    completed: false
  },
  {
    id: '24',
    title: 'Eksplorasi Braga Pagi',
    location: 'Jalan Braga',
    latitude: -6.9147,
    longitude: 107.6098,
    color: '#FFD700',
    icon: 'sun',
    time: 'Setiap Minggu Pagi, 06:00 - 08:00',
    price: 'Gratis',
    contact: 'braga.pagi@email.com',
    fullDescription: 'Jalan santai menikmati suasana Jalan Braga di pagi hari yang tenang dan bersejarah.',
    category: 'all',
    description: 'Eksplorasi pagi di Jalan Braga.',
    date: '2025-12-28',
    activities: ['Jalan Kaki', 'Fotografi', 'Sarapan'],
    points: 10,
    completed: false
  },
  {
    id: '25',
    title: 'Workshop Kerajinan Tanah Liat',
    location: 'Studio Gerabah Pak Budi',
    latitude: -6.8900,
    longitude: 107.6600,
    color: '#A0522D',
    icon: 'hands-helping',
    time: 'Setiap Sabtu, 13:00 - 16:00',
    price: 'Rp 180.000',
    contact: 'pakbudi.gerabah@email.com',
    fullDescription: 'Belajar membuat berbagai kerajinan dari tanah liat, dari pembentukan hingga pewarnaan.',
    category: 'kerajinan',
    discount: 'Diskon 5% untuk pembelian hasil karya',
    description: 'Workshop kerajinan tanah liat.',
    date: '2025-12-29',
    activities: ['Pembentukan Gerabah', 'Pewarnaan', 'Pameran Karya'],
    points: 10,
    completed: false
  },
  {
    id: '26',
    title: 'Gaya Desain Modern',
    location: 'Bandung Design Center',
    latitude: -6.9200,
    longitude: 107.6200,
    color: '#5DADE2',
    icon: 'lightbulb',
    time: '10:00 - 17:00',
    price: 'Rp 75.000',
    contact: 'designcenter@email.com',
    fullDescription: 'Pameran desain interior dan eksterior modern dari desainer Bandung.',
    category: 'seni',
    description: 'Pameran desain modern.',
    date: '2025-12-30',
    activities: ['Pameran', 'Diskusi Desain', 'Networking'],
    points: 10,
    completed: false
  },
  {
    id: '27',
    title: 'Konser Musik Indie',
    location: 'Lapangan PSSI',
    latitude: -6.9300,
    longitude: 107.6300,
    color: '#58D68D',
    icon: 'compact-disc',
    time: '19:00 - Selesai',
    price: 'Rp 50.000',
    contact: 'bandungindie@email.com',
    fullDescription: 'Penampilan band indie lokal dan nasional.',
    category: 'musik',
    discount: 'Early Bird 15%',
    description: 'Konser musik dari band indie.',
    date: '2026-01-01',
    activities: ['Menonton Konser', 'Food Bazaar', 'Meet & Greet'],
    points: 10,
    completed: false
  },
  {
    id: '28',
    title: 'Festival Makanan Pedas',
    location: 'Gasibu',
    latitude: -6.9000,
    longitude: 107.6200,
    color: '#E74C3C',
    icon: 'pepper-hot',
    time: '11:00 - 21:00',
    price: 'Mulai Rp 25.000',
    contact: 'pedasbandung@email.com',
    fullDescription: 'Berbagai macam makanan pedas dari seluruh Indonesia.',
    category: 'kuliner',
    description: 'Festival makanan pedas.',
    date: '2026-01-02',
    activities: ['Food Challenge', 'Food Bazaar', 'Live Cooking'],
    points: 10,
    completed: false
  },
  {
    id: '29',
    title: 'Pameran Kerajinan Kayu',
    location: 'Balai Kota Bandung',
    latitude: -6.9100,
    longitude: 107.6100,
    color: '#AF7AC5',
    icon: 'tree',
    time: '09:00 - 17:00',
    price: 'Gratis',
    contact: 'kayubandung@email.com',
    fullDescription: 'Pameran kerajinan tangan dari kayu jati dan mahoni.',
    category: 'kerajinan',
    description: 'Pameran kerajinan kayu.',
    date: '2026-01-03',
    activities: ['Pameran', 'Workshop', 'Live Demo'],
    points: 10,
    completed: false
  },
  {
    id: '30',
    title: 'Festival Fotografi Malam',
    location: 'Jalan Asia Afrika',
    latitude: -6.9200,
    longitude: 107.6080,
    color: '#34495E',
    icon: 'camera-retro',
    time: '19:00 - 23:00',
    price: 'Gratis',
    contact: 'fotobandung@email.com',
    fullDescription: 'Hunting foto malam di jalanan bersejarah Asia Afrika.',
    category: 'seni',
    description: 'Festival fotografi malam.',
    date: '2026-01-04',
    activities: ['Hunting Foto', 'Workshop', 'Pameran Foto'],
    points: 10,
    completed: false
  },
  {
    id: '31',
    title: 'Gelar Seni Tari Kontemporer',
    location: 'Teater Tertutup Dago Tea House',
    latitude: -6.8500,
    longitude: 107.6100,
    color: '#F1C40F',
    icon: 'users',
    time: '19:00 - 21:00',
    price: 'Rp 60.000',
    contact: 'dagoteahouse@email.com',
    fullDescription: 'Pertunjukan tari kontemporer dari seniman lokal.',
    category: 'seni',
    description: 'Pertunjukan tari kontemporer.',
    date: '2026-01-05',
    activities: ['Menonton Pertunjukan', 'Diskusi', 'Meet & Greet'],
    points: 10,
    completed: false
  },
  {
    id: '32',
    title: 'Workshop Desain Grafis',
    location: 'Bandung Digital Valley',
    latitude: -6.9100,
    longitude: 107.6000,
    color: '#1ABC9C',
    icon: 'paint-roller',
    time: '10:00 - 16:00',
    price: 'Rp 250.000',
    contact: 'digitalvalley@email.com',
    fullDescription: 'Workshop untuk belajar desain grafis menggunakan software terbaru.',
    category: 'kerajinan',
    description: 'Workshop desain grafis.',
    date: '2026-01-06',
    activities: ['Pelatihan Software', 'Proyek Desain', 'Portfolio Review'],
    points: 10,
    completed: false
  },
  {
    id: '33',
    title: 'Festival Kopi Bandung',
    location: 'Cihampelas Walk',
    latitude: -6.8900,
    longitude: 107.6000,
    color: '#D35400',
    icon: 'coffee',
    time: '10:00 - 22:00',
    price: 'Gratis Masuk',
    contact: 'kopibandung@email.com',
    fullDescription: 'Berbagai jenis kopi dari seluruh Indonesia dan dunia.',
    category: 'kuliner',
    discount: 'Diskon 10% untuk pembelian 2 cangkir',
    description: 'Festival kopi terbesar di Bandung.',
    date: '2026-01-07',
    activities: ['Coffee Tasting', 'Workshop Barista', 'Live Music'],
    points: 10,
    completed: false
  },
  {
    id: '34',
    title: 'Pagelaran Wayang Kulit',
    location: 'Museum Sri Baduga',
    latitude: -6.9300,
    longitude: 107.6000,
    color: '#9B59B6',
    icon: 'theater-masks',
    time: '20:00 - Selesai',
    price: 'Rp 35.000',
    contact: 'sribaduga@email.com',
    fullDescription: 'Pertunjukan wayang kulit dengan cerita epik Ramayana.',
    category: 'seni',
    description: 'Pagelaran wayang kulit.',
    date: '2026-01-08',
    activities: ['Menonton Pertunjukan', 'Edukasi Budaya', 'Meet & Greet'],
    points: 10,
    completed: false
  },
  {
    id: '35',
    title: 'Pameran Lukisan Abstrak',
    location: 'Galeri NuArt Sculpture Park',
    latitude: -6.8300,
    longitude: 107.5700,
    color: '#2ECC71',
    icon: 'paint-brush',
    time: '10:00 - 18:00',
    price: 'Rp 40.000',
    contact: 'nuart@email.com',
    fullDescription: 'Koleksi lukisan abstrak dari seniman terkenal.',
    category: 'seni',
    description: 'Pameran lukisan abstrak.',
    date: '2026-01-09',
    activities: ['Melihat Pameran', 'Diskusi', 'Workshop Seni'],
    points: 10,
    completed: false
  },
  {
    id: '36',
    title: 'Festival Band Pelajar',
    location: 'Sabuga ITB',
    latitude: -6.8900,
    longitude: 107.6100,
    color: '#E67E22',
    icon: 'drum',
    time: '14:00 - 22:00',
    price: 'Rp 25.000',
    contact: 'sabuga@email.com',
    fullDescription: 'Kompetisi band antar pelajar se-Bandung.',
    category: 'musik',
    description: 'Festival band pelajar.',
    date: '2026-01-10',
    activities: ['Menonton Kompetisi', 'Food Bazaar', 'Meet & Greet'],
    points: 10,
    completed: false
  },
  {
    id: '37',
    title: 'Workshop Keramik Cantik',
    location: 'Jalan Cibaduyut',
    latitude: -6.9500,
    longitude: 107.5800,
    color: '#8E44AD',
    icon: 'chess-board',
    time: '09:00 - 12:00',
    price: 'Rp 175.000',
    contact: 'keramikcibaduyut@email.com',
    fullDescription: 'Belajar membuat keramik dengan teknik modern dan tradisional.',
    category: 'kerajinan',
    description: 'Workshop membuat keramik.',
    date: '2026-01-11',
    activities: ['Pembuatan Keramik', 'Pewarnaan', 'Pameran Karya'],
    points: 10,
    completed: false
  },
  {
    id: '38',
    title: 'Pasar Kuliner Tradisional',
    location: 'Lapangan Tegalega',
    latitude: -6.9350,
    longitude: 107.6050,
    color: '#2C3E50',
    icon: 'egg',
    time: '08:00 - 17:00',
    price: 'Mulai Rp 10.000',
    contact: 'pasartegalega@email.com',
    fullDescription: 'Berbagai jajanan dan makanan tradisional Bandung.',
    category: 'kuliner',
    description: 'Pasar kuliner tradisional.',
    date: '2026-01-12',
    activities: ['Food Tasting', 'Kuliner Tradisional', 'Live Music'],
    points: 10,
    completed: false
  },
  {
    id: '39',
    title: 'Gelar Karya Seniman Muda',
    location: 'Bandung Creative City Forum',
    latitude: -6.9100,
    longitude: 107.6100,
    color: '#E7B00C',
    icon: 'star',
    time: '13:00 - 20:00',
    price: 'Gratis',
    contact: 'bccf@email.com',
    fullDescription: 'Pameran karya seni dari seniman muda Bandung.',
    category: 'seni',
    description: 'Pameran karya seniman muda.',
    date: '2026-01-13',
    activities: ['Pameran Seni', 'Diskusi Seniman', 'Workshop'],
    points: 10,
    completed: false
  },
  {
    id: '40',
    title: 'Nonton Bareng Film Klasik',
    location: 'Bioskop Majestic',
    latitude: -6.9100,
    longitude: 107.6000,
    color: '#8A8A8A',
    icon: 'video',
    time: '19:00 - 22:00',
    price: 'Rp 20.000',
    contact: 'majestic@email.com',
    fullDescription: 'Pemutaran film klasik Indonesia dan diskusi.',
    category: 'seni',
    description: 'Nonton bareng film klasik.',
    date: '2026-01-14',
    activities: ['Menonton Film', 'Diskusi Film', 'Q&A'],
    points: 10,
    completed: false
  },
  {
    id: '41',
    title: 'Workshop Anyaman Bambu',
    location: 'Kampung Wisata Cinunuk',
    latitude: -6.9000,
    longitude: 107.7000,
    color: '#F4D03F',
    icon: 'leaf',
    time: '10:00 - 15:00',
    price: 'Rp 100.000',
    contact: 'cinunuk@email.com',
    fullDescription: 'Belajar membuat kerajinan anyaman dari bambu.',
    category: 'kerajinan',
    description: 'Workshop anyaman bambu.',
    date: '2026-01-15',
    activities: ['Pelatihan Anyaman', 'Pembuatan Produk', 'Pameran'],
    points: 10,
    completed: false
  },
  {
    id: '42',
    title: 'Festival Budaya Tionghoa',
    location: 'Klenteng Satya Budhi',
    latitude: -6.9200,
    longitude: 107.6000,
    color: '#E0BBE4',
    icon: 'dragon',
    time: '10:00 - 18:00',
    price: 'Gratis',
    contact: 'klenteng@email.com',
    fullDescription: 'Perayaan budaya Tionghoa dengan barongsai, liong, dan kuliner khas.',
    category: 'all',
    description: 'Festival budaya Tionghoa.',
    date: '2026-01-16',
    activities: ['Barongsai', 'Liong', 'Kuliner Khas'],
    points: 10,
    completed: false
  },
  {
    id: '43',
    title: 'Konser Musik Orkestra',
    location: 'Gedung Sate',
    latitude: -6.9025,
    longitude: 107.6189,
    color: '#85C1E9',
    icon: 'music',
    time: '19:00 - 21:00',
    price: 'Rp 150.000',
    contact: 'orchestrabdg@email.com',
    fullDescription: 'Penampilan orkestra simfoni dengan lagu-lagu klasik dan modern.',
    category: 'musik',
    description: 'Konser musik orkestra.',
    date: '2026-01-17',
    activities: ['Menonton Konser', 'Meet & Greet', 'Sesi Foto'],
    points: 10,
    completed: false
  },
  {
    id: '44',
    title: 'Pameran Kaligrafi Arab',
    location: 'Masjid Raya Bandung',
    latitude: -6.9200,
    longitude: 107.6050,
    color: '#AED6F1',
    icon: 'pen-nib',
    time: '09:00 - 17:00',
    price: 'Gratis',
    contact: 'masjidraya@email.com',
    fullDescription: 'Pameran karya kaligrafi dari seniman lokal dan nasional.',
    category: 'seni',
    description: 'Pameran kaligrafi Arab.',
    date: '2026-01-18',
    activities: ['Pameran', 'Workshop Kaligrafi', 'Diskusi'],
    points: 10,
    completed: false
  },
  {
    id: '45',
    title: 'Festival Kuliner Vegan',
    location: 'Kebun Binatang Bandung',
    latitude: -6.8900,
    longitude: 107.6100,
    color: '#ABEBC6',
    icon: 'carrot',
    time: '10:00 - 18:00',
    price: 'Gratis Masuk',
    contact: 'veganbdg@email.com',
    fullDescription: 'Berbagai hidangan vegan dari berbagai restoran di Bandung.',
    category: 'kuliner',
    discount: 'Diskon 10% untuk pembelian di atas Rp 100.000',
    description: 'Festival kuliner vegan.',
    date: '2026-01-19',
    activities: ['Food Tasting', 'Live Cooking', 'Workshop Masak Vegan'],
    points: 10,
    completed: false
  },
  {
    id: '46',
    title: 'Workshop Membuat Lilin Aromaterapi',
    location: 'Home Industri Lilin',
    latitude: -6.9000,
    longitude: 107.6500,
    color: '#FADBD8',
    icon: 'lightbulb',
    time: '14:00 - 17:00',
    price: 'Rp 120.000',
    contact: 'lilinbdg@email.com',
    fullDescription: 'Belajar membuat lilin aromaterapi dengan berbagai bentuk dan aroma.',
    category: 'kerajinan',
    description: 'Workshop membuat lilin aromaterapi.',
    date: '2026-01-20',
    activities: ['Pembuatan Lilin', 'Pewarnaan', 'Penghiasan'],
    points: 10,
    completed: false
  },
  {
    id: '47',
    title: 'Gelar Budaya Sunda Modern',
    location: 'Telkom University Convention Center',
    latitude: -6.9700,
    longitude: 107.6300,
    color: '#F4D03F',
    icon: 'sitemap',
    time: '19:00 - 22:00',
    price: 'Rp 75.000',
    contact: 'telkomuc@email.com',
    fullDescription: 'Pertunjukan seni dan budaya Sunda yang dikemas secara modern.',
    category: 'seni',
    description: 'Gelar budaya Sunda modern.',
    date: '2026-01-21',
    activities: ['Pertunjukan Seni', 'Musik Tradisional', 'Tari Kontemporer'],
    points: 10,
    completed: false
  },
  {
    id: '48',
    title: 'Festival Permainan Tradisional',
    location: 'Taman Lalu Lintas',
    latitude: -6.9100,
    longitude: 107.6100,
    color: '#D7BDE2',
    icon: 'gamepad',
    time: '10:00 - 17:00',
    price: 'Gratis',
    contact: 'tamanlalulintas@email.com',
    fullDescription: 'Berbagai permainan tradisional Indonesia yang bisa dimainkan oleh anak-anak dan dewasa.',
    category: 'all',
    description: 'Festival permainan tradisional.',
    date: '2026-01-22',
    activities: ['Bermain Permainan', 'Lomba Permainan', 'Kuliner Tradisional'],
    points: 10,
    completed: false
  },
  {
    id: '49',
    title: 'Pameran Sketsa Wajah',
    location: 'Jalan Braga',
    latitude: -6.9147,
    longitude: 107.6098,
    color: '#D5DBDB',
    icon: 'portrait',
    time: '15:00 - 21:00',
    price: 'Gratis',
    contact: 'bragasketsa@email.com',
    fullDescription: 'Pameran sketsa wajah dari seniman jalanan Braga.',
    category: 'seni',
    description: 'Pameran sketsa wajah.',
    date: '2026-01-23',
    activities: ['Melihat Pameran', 'Sketsa On The Spot', 'Diskusi'],
    points: 10,
    completed: false
  },
  {
    id: '50',
    title: 'Workshop Fotografi Dasar',
    location: 'Taman Hutan Raya Ir. H. Djuanda',
    latitude: -6.8300,
    longitude: 107.6400,
    color: '#AAB7B8',
    icon: 'camera-retro',
    time: '09:00 - 12:00',
    price: 'Rp 150.000',
    contact: 'tahura@email.com',
    fullDescription: 'Belajar dasar-dasar fotografi dengan teknik yang benar.',
    category: 'seni',
    description: 'Workshop fotografi dasar.',
    date: '2026-01-24',
    activities: ['Pelatihan Fotografi', 'Hunting Foto', 'Editing Foto'],
    points: 10,
    completed: false
  },
];