export interface SeedPoint {
  id: string;
  title: string;
  latitude: number;
  longitude: number;
  location: string;
  description: string;
  icon: string;
  color: string;
}

export const seedPoints: SeedPoint[] = [
  {
    id: '1',
    title: 'Gedung Sate',
    latitude: -6.9025,
    longitude: 107.6189,
    location: 'Bandung',
    description: 'Landmark ikonik Bandung dengan arsitektur Art Deco yang megah.',
    icon: 'building',
    color: '#80bfff',
  },
  {
    id: '2',
    title: 'Museum Konferensi Asia Afrika',
    latitude: -6.9200,
    longitude: 107.6080,
    location: 'Bandung',
    description: 'Situs bersejarah tempat Konferensi Asia-Afrika diselenggarakan pada tahun 1955.',
    icon: 'landmark',
    color: '#90d69c',
  },
  {
    id: '3',
    title: 'Vila Isola',
    latitude: -6.8623,
    longitude: 107.5910,
    location: 'Bandung',
    description: 'Bangunan bersejarah dengan arsitektur yang menawan, kini bagian dari Universitas Pendidikan Indonesia.',
    icon: 'university',
    color: '#b19cd9',
  },
  {
    id: '4',
    title: 'Kawah Putih',
    latitude: -7.6528,
    longitude: 107.4011,
    location: 'Ciwidey',
    description: 'Danau kawah vulkanik dengan air berwarna putih kehijauan yang memukau.',
    icon: 'mountain',
    color: '#89cdd3',
  },
  {
    id: '5',
    title: 'Tangkuban Perahu',
    latitude: -6.7593,
    longitude: 107.6094,
    location: 'Lembang',
    description: 'Gunung berapi aktif dengan kawah berbentuk perahu terbalik.',
    icon: 'fire',
    color: '#ff9b9b',
  },
  {
    id: '6',
    title: 'Kebun Teh Rancabali',
    latitude: -7.1648,
    longitude: 107.4098,
    location: 'Ciwidey',
    description: 'Hamparan kebun teh yang hijau dan asri, cocok untuk relaksasi.',
    icon: 'leaf',
    color: '#94dacc',
  },
  {
    id: '7',
    title: 'Farmhouse Lembang',
    latitude: -6.8202,
    longitude: 107.6067,
    location: 'Lembang',
    description: 'Destinasi wisata keluarga dengan nuansa peternakan Eropa.',
    icon: 'tractor',
    color: '#ffc880',
  },
  {
    id: '8',
    title: 'Floating Market Lembang',
    latitude: -6.8152,
    longitude: 107.6081,
    location: 'Lembang',
    description: 'Pasar terapung dengan beragam kuliner dan wahana air.',
    icon: 'ship',
    color: '#a9b1b7',
  },
  {
    id: '9',
    title: 'Orchid Forest Cikole',
    latitude: -6.7720,
    longitude: 107.6470,
    location: 'Cikole',
    description: 'Hutan pinus dengan koleksi anggrek yang indah dan berbagai aktivitas outdoor.',
    icon: 'tree',
    color: '#8bd9ca',
  },
  {
    id: '10',
    title: 'The Great Asia Africa',
    latitude: -6.8170,
    longitude: 107.6060,
    location: 'Lembang',
    description: 'Wisata edukasi dan budaya dengan miniatur negara-negara Asia dan Afrika.',
    icon: 'globe-asia',
    color: '#f4a8cb',
  },
  {
    id: '11',
    title: 'Dusun Bambu Family Leisure Park',
    latitude: -6.8048,
    longitude: 107.5492,
    location: 'Lembang',
    description: 'Resor ramah keluarga dengan taman, restoran, dan aktivitas alam.',
    icon: 'pagelines',
    color: '#ad85ff',
  },
  {
    id: '12',
    title: 'Curug Cimahi (Pelangi)',
    latitude: -6.7925,
    longitude: 107.5750,
    location: 'Cisarua',
    description: 'Air terjun yang memancarkan warna pelangi saat terkena sinar matahari.',
    icon: 'water',
    color: '#87ceeb',
  },
  {
    id: '13',
    title: 'Situ Patenggang',
    latitude: -7.3195,
    longitude: 107.3506,
    location: 'Ciwidey',
    description: 'Danau indah dengan legenda perahu cinta, cocok untuk berperahu.',
    icon: 'anchor',
    color: '#a4dce9',
  },
  {
    id: '14',
    title: 'Glamping Lakeside Rancabali',
    latitude: -7.3200,
    longitude: 107.3500,
    location: 'Ciwidey',
    description: 'Pengalaman glamping mewah di tepi danau dengan pemandangan menakjubkan.',
    icon: 'campground',
    color: '#ffe082',
  },
  {
    id: '15',
    title: 'Ranca Upas',
    latitude: -7.3100,
    longitude: 107.3900,
    location: 'Ciwidey',
    description: 'Area camping dan penangkaran rusa yang populer di Ciwidey.',
    icon: 'deer',
    color: '#b19cd9',
  },
  {
    id: '16',
    title: 'Ciwidey Valley Resort Hot Spring & Waterpark',
    latitude: -7.3200,
    longitude: 107.3900,
    location: 'Ciwidey',
    description: 'Resor dengan pemandian air panas alami dan taman air seru.',
    icon: 'swimmer',
    color: '#89cdd3',
  },
  {
    id: '17',
    title: 'Trans Studio Bandung',
    latitude: -6.9200,
    longitude: 107.6360,
    location: 'Bandung',
    description: 'Taman hiburan indoor terbesar di Bandung dengan berbagai wahana seru.',
    icon: 'roller-coaster',
    color: '#ff9b9b',
  },
  {
    id: '18',
    title: 'Bandung Zoo',
    latitude: -6.8900,
    longitude: 107.6100,
    location: 'Bandung',
    description: 'Kebun binatang dengan koleksi satwa dari berbagai belahan dunia.',
    icon: 'paw',
    color: '#90d69c',
  },
  {
    id: '19',
    title: 'Paskal Hyper Square',
    latitude: -6.9180,
    longitude: 107.5990,
    location: 'Bandung',
    description: 'Kompleks perbelanjaan modern dan kuliner yang ramai.',
    icon: 'shopping-bag',
    color: '#80bfff',
  },
  {
    id: '20',
    title: 'Cihampelas Walk',
    latitude: -6.8950,
    longitude: 107.5990,
    location: 'Bandung',
    description: 'Pusat perbelanjaan outdoor dengan konsep pedestrian yang unik.',
    icon: 'walking',
    color: '#ffc880',
  },
  {
    id: '21',
    title: 'Paris Van Java Resort Lifestyle Place',
    latitude: -6.8870,
    longitude: 107.5990,
    location: 'Bandung',
    description: 'Mal bergaya Eropa dengan butik, restoran, dan hiburan.',
    icon: 'store',
    color: '#b19cd9',
  },
  {
    id: '22',
    title: 'Braga CityWalk',
    latitude: -6.9160,
    longitude: 107.6080,
    location: 'Bandung',
    description: 'Pusat perbelanjaan dan hiburan di Jalan Braga yang bersejarah.',
    icon: 'city',
    color: '#a9b1b7',
  },
  {
    id: '23',
    title: 'Bandung Indah Plaza',
    latitude: -6.9070,
    longitude: 107.6100,
    location: 'Bandung',
    description: 'Salah satu mal tertua di Bandung dengan berbagai tenant.',
    icon: 'shopping-cart',
    color: '#f4a8cb',
  },
  {
    id: '24',
    title: 'Factory Outlet Jalan Riau',
    latitude: -6.9070,
    longitude: 107.6200,
    location: 'Bandung',
    description: 'Deretan factory outlet populer untuk berburu fashion dengan harga menarik.',
    icon: 'tshirt',
    color: '#94dacc',
  },
  {
    id: '25',
    title: 'The Lodge Maribaya',
    latitude: -6.7900,
    longitude: 107.6700,
    location: 'Lembang',
    description: 'Destinasi wisata alam dengan spot foto Instagramable dan aktivitas outdoor.',
    icon: 'camera-retro',
    color: '#ffe082',
  },
];